name: project_checker

on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  check_program_compilation:
    if: ${{vars.MIRROR_URL != ''}}
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Xvfb and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libx11-dev libgl1-mesa-dev libsfml-dev
      - name: Check for build.sh
        run: |
          if [ ! -f "build.sh" ]; then
            echo "::error ::/!\\ WARNING NO build.sh FOUND /!\\"
            exit 84
          else
            echo "::notice::build.sh found."
          fi
      # - name: Launch ./build.sh
      #   run: |
      #     if ./build.sh; then
      #       echo "::notice file=build.sh::Succesfully compilation (./build.sh)."
      #     else
      #       echo "::error file=build.sh::/!\\ COMPILATION ERROR (./build.sh)/!\\"
      #       exit 84
      #     fi
      # - name: Check executables
      #   run: |
      #     executable="${EXECUTABLE_PATH}"
      #     if [ ! -x "$executable" ]; then
      #       echo "::error file=$executable::Executable $executable is missing or not executable."
      #       exit 84
      #     else
      #       echo "::notice file=$executable::Executable $executable found and is executable."
      #     fi
      #   env:
      #     EXECUTABLE_PATH: ${{ vars.EXECUTABLE_PATH }}
      - name: Check unit_tests
        run: |
          if xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" ./build.sh --tests ; then
            echo "::notice file=build.sh::Unit tests successful (./build.sh --tests)."
          else
            echo "::error file=build.sh::/!\\ UNIT TESTS ERROR (./build.sh --tests)/!\\"
            exit 84
          fi
        env:
          EXECUTABLE_PATH: ${{ vars.EXECUTABLE_PATH }}
          DISPLAY: ":99"
